name: CI/CD

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@master

    - name: Docker Build Tag Push
      run: |
        IMAGE_NAME="docker.pkg.github.com/${GITHUB_REPOSITORY}/qbittorrent:${GITHUB_REF##*/}-v${GITHUB_RUN_NUMBER}"
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
